linters:
  enable:
    - gofmt        # Keep basic formatting
    - govet        # Reports suspicious constructs
    - errcheck     # Checks for unchecked errors
    - staticcheck  # Advanced static analysis
    - gosimple     # Simplifies code
    - bodyclose    # Checks whether HTTP response bodies are closed
    - gocritic     # Checks for performance optimizations
    - gosec        # Security checks
    - prealloc     # Suggests slice preallocation

linters-settings:
  gocritic:
    enabled-tags:
      - performance
      - diagnostic
    disabled-checks:
      - commentedOutCode
  gosec:
    excludes:
      - G104  # Duplicate of errcheck

run:
  timeout: 5m

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0 