services:
  email-validator:
    image: umutert/emailvalidator:latest
    ports:
      - "1001:8080"
    environment:
      - PROMETHEUS_ENABLED=true
      - REDIS_URL=redis://redis:6379
    depends_on:
      - prometheus
      - redis
    networks:
      - app-network

  proxy-validator-service:
    build: ./proxy-validator-service
    ports:
      - "2002:3001"
    environment:
      - PORT=3001
      - GO_VALIDATOR_API_URL=http://email-validator:8080/api/validate
      - DISPOSABLE_DOMAINS_URL=${DISPOSABLE_DOMAINS_URL}
      - REFRESH_INTERVAL_HOURS=${REFRESH_INTERVAL_HOURS}
    depends_on:
      - email-validator
    networks:
      - app-network

  redis:
    image: redis:alpine
    ports:
      - "3003:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes
    networks:
      - app-network

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "4004:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    networks:
      - app-network

  grafana:
    image: grafana/grafana:latest
    ports:
      - "5005:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - grafana-storage:/var/lib/grafana
    depends_on:
      - prometheus
    networks:
      - app-network

volumes:
  grafana-storage: {}
  redis-data: {}

networks:
  app-network:
    driver: bridge